#! /bin/env/node

var app = require('../app');

app.set('ip', '0.0.0.0');
app.set('port', process.env.PORT || 9090);

app.listen(app.get('port'), app.get('ip'), function() {
    process.stdout.write('Listening on port ' + app.get('port'));
});
